name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: PrettyScatter.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release
      
    - name: Build the application
      run: msbuild $env:Solution_Name /t:Build /p:Configuration=Release
      
    - name: ls 1
      run: ls
      
    - name: ls 2
      run: ls bin
      
    - name: ls 3
      run: ls bin/Releases
      
    - name: Compress the artifact
      run: powershell compress-archive bin/Releases/net5.0-windows/* PrettyScatter.zip

    - name: Update the .exe artifact to GitHub Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          PrettyScatter.zip
